"""Add progress tracking tables

Revision ID: 83d9858f5e75
Revises: ecba55ec568f
Create Date: 2025-10-13 21:11:32.995562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83d9858f5e75'
down_revision: Union[str, None] = 'ecba55ec568f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_specialist_favorite_created'), table_name='specialist_favorites')
    op.drop_index(op.f('idx_specialist_favorite_patient'), table_name='specialist_favorites')
    op.drop_index(op.f('idx_specialist_favorite_specialist'), table_name='specialist_favorites')
    op.drop_index(op.f('ix_specialist_favorites_created_at'), table_name='specialist_favorites')
    op.drop_index(op.f('ix_specialist_favorites_patient_id'), table_name='specialist_favorites')
    op.drop_index(op.f('ix_specialist_favorites_specialist_id'), table_name='specialist_favorites')
    op.drop_table('specialist_favorites')
    op.alter_column('forum_questions', 'patient_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_forum_questions_specialist_id'), 'forum_questions', ['specialist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forum_questions_specialist_id'), table_name='forum_questions')
    op.alter_column('forum_questions', 'patient_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_table('specialist_favorites',
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('specialist_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('specialist_favorites_patient_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialist_id'], ['specialists.id'], name=op.f('specialist_favorites_specialist_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('specialist_favorites_pkey')),
    sa.UniqueConstraint('patient_id', 'specialist_id', name=op.f('uq_patient_specialist_favorite'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_specialist_favorites_specialist_id'), 'specialist_favorites', ['specialist_id'], unique=False)
    op.create_index(op.f('ix_specialist_favorites_patient_id'), 'specialist_favorites', ['patient_id'], unique=False)
    op.create_index(op.f('ix_specialist_favorites_created_at'), 'specialist_favorites', ['created_at'], unique=False)
    op.create_index(op.f('idx_specialist_favorite_specialist'), 'specialist_favorites', ['specialist_id'], unique=False)
    op.create_index(op.f('idx_specialist_favorite_patient'), 'specialist_favorites', ['patient_id'], unique=False)
    op.create_index(op.f('idx_specialist_favorite_created'), 'specialist_favorites', ['created_at'], unique=False)
    # ### end Alembic commands ###
