"""Add progress tracking tables v2

Revision ID: e6a3125ec3eb
Revises: 83d9858f5e75
Create Date: 2025-10-13 21:13:08.310017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a3125ec3eb'
down_revision: Union[str, None] = '83d9858f5e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_progress',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('exercise_name', sa.String(length=255), nullable=False),
    sa.Column('exercise_category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='exercisestatus'), nullable=False),
    sa.Column('completion_count', sa.Integer(), nullable=False),
    sa.Column('total_time_seconds', sa.Integer(), nullable=False),
    sa.Column('first_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('average_mood_improvement', sa.Float(), nullable=True),
    sa.Column('effectiveness_rating', sa.Float(), nullable=True),
    sa.Column('mastery_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='masterylevel'), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'exercise_name', name='uq_patient_exercise')
    )
    op.create_index('idx_progress_favorite', 'exercise_progress', ['is_favorite'], unique=False)
    op.create_index('idx_progress_mastery', 'exercise_progress', ['mastery_level'], unique=False)
    op.create_index('idx_progress_patient', 'exercise_progress', ['patient_id'], unique=False)
    op.create_index('idx_progress_patient_exercise', 'exercise_progress', ['patient_id', 'exercise_name'], unique=False)
    op.create_index('idx_progress_status', 'exercise_progress', ['status'], unique=False)
    op.create_table('exercise_sessions',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('exercise_name', sa.String(length=255), nullable=False),
    sa.Column('exercise_category', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('mood_before', sa.Integer(), nullable=True),
    sa.Column('mood_after', sa.Integer(), nullable=True),
    sa.Column('mood_improvement', sa.Integer(), nullable=True),
    sa.Column('steps_completed', sa.JSON(), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('session_completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('time_of_day', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', 'NIGHT', name='timeofday'), nullable=True),
    sa.Column('location_type', sa.Enum('HOME', 'WORK', 'OUTDOOR', 'OTHER', name='locationtype'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_completed', 'exercise_sessions', ['session_completed'], unique=False)
    op.create_index('idx_session_exercise', 'exercise_sessions', ['exercise_name'], unique=False)
    op.create_index('idx_session_patient', 'exercise_sessions', ['patient_id'], unique=False)
    op.create_index('idx_session_patient_date', 'exercise_sessions', ['patient_id', 'start_time'], unique=False)
    op.create_index('idx_session_start_time', 'exercise_sessions', ['start_time'], unique=False)
    op.create_table('practice_calendar',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('practice_date', sa.Date(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('exercises_practiced', sa.JSON(), nullable=True),
    sa.Column('intensity_level', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'practice_date', name='uq_patient_practice_date')
    )
    op.create_index('idx_calendar_date', 'practice_calendar', ['practice_date'], unique=False)
    op.create_index('idx_calendar_intensity', 'practice_calendar', ['intensity_level'], unique=False)
    op.create_index('idx_calendar_patient', 'practice_calendar', ['patient_id'], unique=False)
    op.create_index('idx_calendar_patient_date', 'practice_calendar', ['patient_id', 'practice_date'], unique=False)
    op.create_table('user_achievements',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.String(length=100), nullable=False),
    sa.Column('achievement_name', sa.String(length=200), nullable=False),
    sa.Column('achievement_description', sa.Text(), nullable=True),
    sa.Column('achievement_icon', sa.String(length=50), nullable=True),
    sa.Column('achievement_category', sa.Enum('STREAK', 'COMPLETION', 'VARIETY', 'MASTERY', 'SPECIAL', name='achievementcategory'), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('progress_value', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', name='achievementrarity'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_notified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'achievement_id', name='uq_patient_achievement')
    )
    op.create_index('idx_achievement_category', 'user_achievements', ['achievement_category'], unique=False)
    op.create_index('idx_achievement_patient', 'user_achievements', ['patient_id'], unique=False)
    op.create_index('idx_achievement_rarity', 'user_achievements', ['rarity'], unique=False)
    op.create_index('idx_achievement_unlocked', 'user_achievements', ['unlocked_at'], unique=False)
    op.create_table('user_goals',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('goal_type', sa.Enum('DAILY_PRACTICE', 'WEEKLY_PRACTICE', 'EXERCISE_VARIETY', 'STREAK_MILESTONE', 'TOTAL_SESSIONS', 'SPECIFIC_EXERCISE', 'TIME_BASED', 'MOOD_IMPROVEMENT', 'CUSTOM', name='goaltype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('target_exercise_name', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'FAILED', 'ARCHIVED', name='goalstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reward_badge_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_goal_deadline', 'user_goals', ['deadline'], unique=False)
    op.create_index('idx_goal_patient', 'user_goals', ['patient_id'], unique=False)
    op.create_index('idx_goal_status', 'user_goals', ['status'], unique=False)
    op.create_index('idx_goal_type', 'user_goals', ['goal_type'], unique=False)
    op.create_table('user_streaks',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_practice_date', sa.Date(), nullable=True),
    sa.Column('streak_start_date', sa.Date(), nullable=True),
    sa.Column('longest_streak_start', sa.Date(), nullable=True),
    sa.Column('longest_streak_end', sa.Date(), nullable=True),
    sa.Column('total_practice_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id'),
    sa.UniqueConstraint('patient_id', name='uq_patient_streak')
    )
    op.create_index('idx_streak_current', 'user_streaks', ['current_streak'], unique=False)
    op.create_index('idx_streak_longest', 'user_streaks', ['longest_streak'], unique=False)
    op.create_index('idx_streak_patient', 'user_streaks', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_streak_patient', table_name='user_streaks')
    op.drop_index('idx_streak_longest', table_name='user_streaks')
    op.drop_index('idx_streak_current', table_name='user_streaks')
    op.drop_table('user_streaks')
    op.drop_index('idx_goal_type', table_name='user_goals')
    op.drop_index('idx_goal_status', table_name='user_goals')
    op.drop_index('idx_goal_patient', table_name='user_goals')
    op.drop_index('idx_goal_deadline', table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_index('idx_achievement_unlocked', table_name='user_achievements')
    op.drop_index('idx_achievement_rarity', table_name='user_achievements')
    op.drop_index('idx_achievement_patient', table_name='user_achievements')
    op.drop_index('idx_achievement_category', table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index('idx_calendar_patient_date', table_name='practice_calendar')
    op.drop_index('idx_calendar_patient', table_name='practice_calendar')
    op.drop_index('idx_calendar_intensity', table_name='practice_calendar')
    op.drop_index('idx_calendar_date', table_name='practice_calendar')
    op.drop_table('practice_calendar')
    op.drop_index('idx_session_start_time', table_name='exercise_sessions')
    op.drop_index('idx_session_patient_date', table_name='exercise_sessions')
    op.drop_index('idx_session_patient', table_name='exercise_sessions')
    op.drop_index('idx_session_exercise', table_name='exercise_sessions')
    op.drop_index('idx_session_completed', table_name='exercise_sessions')
    op.drop_table('exercise_sessions')
    op.drop_index('idx_progress_status', table_name='exercise_progress')
    op.drop_index('idx_progress_patient_exercise', table_name='exercise_progress')
    op.drop_index('idx_progress_patient', table_name='exercise_progress')
    op.drop_index('idx_progress_mastery', table_name='exercise_progress')
    op.drop_index('idx_progress_favorite', table_name='exercise_progress')
    op.drop_table('exercise_progress')
    # ### end Alembic commands ###
